local filename=$1
local contentname=$2
# ROUTE_FILENAME=$(basename "${filename}")
# ROUTE_PATH=$SELECTED_USERNAME/$ROUTE_FILENAME.tsx
# ROUTE_PATH=$SELECTED_USERNAME/$ROUTE_FILENAME.tsx
ROUTE_BOILERPLATE=$(<$SCRIPTPATH/templates/routes/${filename}.tsx)
ROUTE_CODE=${ROUTE_BOILERPLATE//REPLACE/$SELECTED_USERNAME}