MOCK_FILENAME=$(basename "$SELECTED_USERNAME")
MOCK_PATH=$SELECTED_USERNAME/mocks/__mock.ts
MOCK_BOILERPLATE=$(<$SCRIPTPATH/templates/mock/mock.ts)
MOCK_CODE=${MOCK_BOILERPLATE//REPLACE/$SELECTED_USERNAME}
